# 服务器
server:
  port: 8081
  servlet:
    session:
      timeout: 172800 # 过期时间为2天

# 日志
logging:
  level:
    root: warn

spring:
  # 数据源
  datasource:
    username: ####
    password: ####
    url: jdbc:mysql://localhost:3306/graduationdesign?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 邮箱
  mail:
    host: smtp.qq.com
    port: 587
    username: ####
    password: ####
  # redis
  redis:
    host: ####
    password: ####
    port: 6379
    jedis:
      pool:
        max-active: 50 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 2   #连接池中的最小空闲连接
        min-idle: 20  #连接池中的最大空闲连接
    timeout: 5000   #连接超时时间（毫秒）
  # 缓存
  cache:
    type: redis
    cache-names: user
    redis:
      time-to-live: 600000 # cache的生存时间为10分钟
  # 会话
  session:
    store-type: redis # 由redis提供session支持
    redis:
      flush-mode: on_save # 当请求完成响应后，才开始同步
      namespace: spring:session # 命名空间
  # thymeleaf引擎
#  thymeleaf:
#    cache: false # 禁用缓存
  # 热部署
  devtools:
    restart:
      enabled: true
  # servlet
  servlet:
    multipart:
      max-file-size: 1MB # 设置单个文件最大尺寸

# mybatis-plus
mybatis-plus:
  global-config:
    banner: false # 关闭banner

## 以下为自定义
# 文件上传
file:
  imagesfolder: C:/Users/####/####/src/main/resources/static/assets/images/user
# 管理员
admin:
  email: admin@admin.com